baseURL = "https://bonkowski.net/"
canonifyURLs = true 
#baseURL = "https://bonkowski.github.io/blog/" 
languageCode = "en-us"
title = "Bonkowski.net"
theme = "cactus"

themesDir = "./themes"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-37909515-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = "andreb"

[taxonomies]
  tag = "tags"
  category = "categories"


[params]
	name = "André Bonkowski"
	description = "Describe your website"
	bio = "Programmer"
	# Enter optionally your twitter account
	twitter = "bonkowski"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I'm an Programmer."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/"
    facebook = "https://www.facebook.com/"
    github   = "https://www.github.com/"
